### ISSUE TITLE
supported Bluetooth proxies

### ISSUE THREAD

**Issue by danigarciaf** [david-collett/panasonic_hc#4]
Thanks for the effort. It works fine for me and it's great to have control from HA. It would be great if it was supported Bluetooth proxies because I have coverage problems due to the distance.

**Comment by david-collett** [comment]
I don't think the integration needs to change to support bluetooth proxies. The trick is getting a bluetooth proxy to reliably pair(bond) and connect. I had some mixed success trying this a while ago. You have to support the "numeric comparison" bluetooth paring scheme in the proxy. the esphome config looks a bit like this:

```
api:
  ...
  services:
    - service: passkey_reply
      variables:
        passkey: int
      then:
        - logger.log: "Authenticating with passkey"
        - ble_client.passkey_reply:
            id: my_ble_client
            passkey: !lambda return passkey;
    - service: numeric_comparison_reply
      variables:
        accept: bool
      then:
        - logger.log: "Authenticating with numeric comparison"
        - ble_client.numeric_comparison_reply:
            id: my_ble_client
            accept: !lambda return accept;

esp32_ble:
  io_capability: keyboard_display

ble_client:
- mac_address: "c5:f6:80:7d:a7:d4"
  id: my_ble_client
  auto_connect: false
  on_passkey_request:
    then:
      - logger.log: "Enter the passkey displayed on your BLE device"
      - logger.log: " Go to https://my.home-assistant.io/redirect/developer_services/ and select passkey_reply"
  on_passkey_notification:
    then:
      - logger.log:
          format: "Enter this passkey on your BLE device: %06d"
          args: [ passkey ]
  on_numeric_comparison_request:
    then:
      - logger.log:
          format: "Compare this passkey with the one on your BLE device: %06d"
          args: [ passkey ]
      - logger.log: " Go to https://my.home-assistant.io/redirect/developer_services/ and select numeric_comparison_reply"
  on_connect:
    then:
        - logger.log: "Connected"
```

When the proxy connects to the panasonic, you have to quickly execute the numeric_comparison_reply service from home assistant and they will become paired. I think my issue was that the bonding data was not stored(persisted) so you had to do this each time the proxy restarted (not sure). There is some discussion about this in a thread regarding another aircon unit here, perhaps it will help. Let me know how you go.

https://community.home-assistant.io/t/daikin-madoka-brc1h-bluetooth-custom-component/268594/196?page=10

Dave

**Comment by danigarciaf** [comment]
Thank you very much David. I checked that it works correctly and maintains the pairing after shutdowns or restarts.

```
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""
  services:
    - service: passkey_reply
      variables:
        passkey: int
      then:
        - logger.log: "Authenticating with passkey"
        - ble_client.passkey_reply:
            id: my_ble_client
            passkey: !lambda return passkey;
    - service: numeric_comparison_reply
      variables:
        accept: bool
      then:
        - logger.log: "Authenticating with numeric comparison"
        - ble_client.numeric_comparison_reply:
            id: my_ble_client
            accept: !lambda return accept;

  
esp32_ble:
  io_capability: keyboard_display


ble_client: 
  - mac_address: "C5:F6:80:7D:A7:D5" # Reemplaza con la dirección MAC de tu termostato
    id: my_ble_client
    auto_connect: false
            
    on_passkey_request:
      then:
        - logger.log: "Enter the passkey displayed on your BLE device"
        - logger.log: " Go to https://my.home-assistant.io/redirect/developer_services/ and select passkey_reply"
    on_passkey_notification:
      then:
        - logger.log:
            format: "Enter this passkey on your BLE device: %06d"
            args: [ passkey ]
    on_numeric_comparison_request:
      then:
        - logger.log:
            format: "Compare this passkey with the one on your BLE device: %06d"
            args: [ passkey ]
        - logger.log: " Go to https://my.home-assistant.io/redirect/developer_services/ and select numeric_comparison_reply"
    on_connect:
      then:
        - logger.log: "Connected"
    


bluetooth_proxy:
  active: true

esp32_ble_tracker:

```
