### ISSUE TITLE
Add switching between Indoor unit and Remote controller temperature sensors?

### ISSUE THREAD

**Issue by pdessart** [david-collett/panasonic_hc#5]
First, thanks so much for putting this together. I'm just in the process of getting a multi-zone Panasonic ducted system installed. I have CZ-RTC6WBLW controllers, so trying to decide how to integrate with HA - WiFi vs, Bluetooth.

To integrate via Bluetooth I'm not sure I won't need to maintain multiple pairings (one for each zone's controller). OTOH, the Comfort Cloud is reportedly unreliable, and I do prefer local vs. cloud integrations.

The "killer app" capability for me in the H&C app (as inconvenient as it is to switch BT connections all the time) is the ability to change whether a zone's thermostatic control is driven by the temperature at the wall controller or at an indoor unit (specifically at the end of its return duct). I have one zone in particular covering 2 rooms where the return duct is only an accurate source for one of the rooms, and the controller is only an accurate source for the other.

Is it at all possible to incorporate the selection of which temperature sensor the zone is driven by? (In the app, this is under "Initial settings" in the "Administrator settings" menu.)

Thanks,
Peter

**Comment by david-collett** [comment]
Hi Peter, this should be possible, however I don't have a remote sensor, so I may not be able to generate the necessary bluetooth packets with the app in order to reverse-engineer the commands. Do you need to change this setting often? Can you not just set it to what you want from the app once, and be done with it?

As an aside, I've found the panasonic controller to be kinda annoying, perhaps I can change this, but mine seems to have a temp tolerance of 2c, meaning the difference between coming on and turning off is 4c, which is *way* too much variance.

Just yesterday I made a "generic thermostat" helper in home assistant that instead uses an average of my (non-panasonic) room thermometers, and just cycles the aircon on and off to keep it within .6c (.3 either side). It's so much better. To do this I had to make a template switch to turn on and off the panasonic, can provide details if interested.

**Comment by pdessart** [comment]
Thanks David. Panasonic's model for how you'd select which sensor (built-in to the wall controller, or internal to the indoor unit) is exactly what you suggest: set it from the app once and be done with it. That's why it's buried in an admin menu, requiring entering a pin.

My situation is a bit different because of the zone I described which covers 2 rooms. Especially if either door is closed, one or the other of the rooms will be too hot or cold depending on which sensor is used.

I will say that creating a virtual thermostat in HA by externally controlling the Panasonic (by looking at per-room non-Panasonic sensors) is something I have considered as an alternative to trying to find a way to switch between which Panasonic sensor is controlling the zone. So yes, I'd love to learn more if you're willing to post your template switch configuration...

**Comment by david-collett** [comment]
Hi Peter,
Here's the switch, I created it in the configuration.yaml file.

Note that turning it on performs two actions, first set the temp to 2.5c below what the unit itself is measuring to ensure it goes straight to cooling and not idle, then set the hvac mode from off to cool. You could do additional things like set fan speed etc too if you wanted to. Note that I've only had this running for one day, but so far so good.  I guess I'll have to make a similar one for heating in winter.

Once the switch is created, you can create the thermostat in the UI from Settings / Devices and Services / Helpers / Create Helper / Generic Thermostat.

Dave

```
switch:
  - platform: template
    switches:
      cooling:
        value_template: "{{ is_state('climate.cz_rtc6blw_7da7d4_thermostat', 'cool') }}"
        turn_on:
          - action: climate.set_temperature
            target:
              entity_id: climate.cz_rtc6blw_7da7d4_thermostat
            data:
              temperature: "{{ state_attr('climate.cz_rtc6blw_7da7d4_thermostat', 'current_temperature') | float - 2.5 }}"
          - action: climate.set_hvac_mode
            target:
              entity_id: climate.cz_rtc6blw_7da7d4_thermostat
            data:
              hvac_mode: "cool"
    
        turn_off:
          - action: climate.set_hvac_mode
            target:
              entity_id: climate.cz_rtc6blw_7da7d4_thermostat
            data:
              hvac_mode: "off"
```
